### ISSUE TITLE
徙主機工課

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/gu2-im1_pian7-sik4#1]
### 前端
- [ ] 改前端程式 #2
- [x] 向資訊室改domain name GitHub io #3
- [x] 自動deploy gh-page(會當莫做) #4

### 後端
- [x] 開一台2cpu/4g vm
- [x] 叫Sîng-hông共kaldı model傳到vm內
- [x] 設定`nginx`domain name，`asr-backend.iis.sinica.edu.tw`
  - ssh tl@10.32.0.126
#### docker解決方案
- [x] kaldi=>dockerhub(會當莫做) #5
- [x] hok8-bu7的dockerfile加kaldi程式 #6
#### 貧惰方案
- [ ] Sîng-hông直接rsync處理

**Comment by leo424y** [comment]
報告 @sih4sing5hong5  已將你的key 加到 TL 2CPU/4G主機囉 
ssh tl@10.32.0.126
